apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
    app: frontend
    tier: api
    project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: api
        project: expense
    spec:
      containers:
      - name: frontend
        images: joimdevops/frontend:v1
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: api
    project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#  name: backend
#  namespace: expense
# spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: backend
#  minReplicas: 1
#  maxReplicas: 10
#  targetCPUUtilizationPercentage: 15 # usually 75 in real environment